version: "3"
services:
  scoutsevents-api:
    image: "welchie99/scoutsevents:${API_VERSION}"
    ports:
      - "8080:8080"
    environment:
      - API_VERSION=${API_VERSION}
      - UI_VERSION=${UI_VERSION}
    healthcheck:
      test: netstat -lan | grep 8080 | wc -l
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - mynet
  scoutsevents-ui:
    image: "welchie99/scoutsevents-ui:${UI_VERSION}"
    ports:
      - "80:3000"
    healthcheck:
      test: netstat -lan | grep 3000 | wc -l
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - mynet
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

networks:
  mynet:


